# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 04:01
from __future__ import unicode_literals

import apps.uploads_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_and_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=apps.uploads_app.models.get_upload_path)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('viewed', models.CharField(default=b'NEW', max_length=75)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_and_registration_app.User')),
            ],
        ),
    ]
