# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 20:09
from __future__ import unicode_literals

import apps.uploads_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=apps.uploads_app.models.get_upload_path),
        ),
    ]
